### ISSUE TITLE
Unable to add Panic! At The Disco DLC maps to playlists

### ISSUE THREAD

**Issue by Miv2nir** [rithik-b/PlaylistManager#60] opened 2023-05-04 10:36 UTC
Effective on versions 1.29.0, 1.29.1, unable to add any of the latest Panic! At The Disco maps to any playlist. 
The menu where to do it does work but after selecting a playlist it just says that it added the map to one, however nothing actually happens.

**Comment by Meivyn** [comment] 2023-10-11 02:49
Duplicate of #50.

**Closed as completed** 2023-10-11 07:45 UTC
